### ISSUE TITLE
Only shows Experiments on Kerbin, all other bodies give errors, even Mun

### ISSUE THREAD

**Issue by Awfullyfishy** [thewebbooth/KSP-X-Science#22]
Using Kopernicus. ResearchBodies  and OPM and a whole load of other mods, so I'm unsure what the cause is but even just going to Minmus doesn't update the [X] Science! window and keeps it saying Kerbin's Water or whatever, here's the error log when I enter orbit around Minmus:

```
[EXC 14:35:31.985] IndexOutOfRangeException: Array index is out of range.
	CBAttributeMapSO.GetAtt (Double lat, Double lon)
	ScienceUtil.GetExperimentBiome (.CelestialBody body, Double lat, Double lon)
	ScienceChecklist.xScienceEventHandler.RecalculateSituation ()
	ScienceChecklist.xScienceEventHandler.UpdateSituation ()
	ScienceChecklist.xScienceEventHandler.Update ()
	ScienceChecklist.ScienceChecklistAddon.Update ()
[ERR 14:35:32.129] [ContractParameter] - Call to OnUpdate failed System.IndexOutOfRangeException: Array index is out of range.
  at CBAttributeMapSO.GetAtt (Double lat, Double lon) [0x00000] in <filename unknown>:0 
  at ScienceUtil.GetExperimentBiome (.CelestialBody body, Double lat, Double lon) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Parameters.CollectScienceCustom.OnUpdate () [0x00000] in <filename unknown>:0 
  at Contracts.ContractParameter.Update () [0x00000] in <filename unknown>:0 

[ERR 14:35:32.380] [ContractParameter] - Call to OnUpdate failed System.IndexOutOfRangeException: Array index is out of range.
  at CBAttributeMapSO.GetAtt (Double lat, Double lon) [0x00000] in <filename unknown>:0 
  at ScienceUtil.GetExperimentBiome (.CelestialBody body, Double lat, Double lon) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Parameters.CollectScienceCustom.OnUpdate () [0x00000] in <filename unknown>:0 
  at Contracts.ContractParameter.Update () [0x00000] in <filename unknown>:0 
```

Unsure what to do to troubleshoot, would love any help as I have no clue where to begin.

[KSP.log](https://github.com/thewebbooth/KSP-X-Science/files/1731523/KSP.log)

**Comment by thewebbooth** [comment]
ScienceUtil.GetExperimentBiome is a KSP built in function. Why it should be failing I don't know.  I'll try and find out.

**Comment by Awfullyfishy** [comment]
Even with [X] Science uninstalled, I still get this error around Minmus:

```
[ERR 15:04:58.214] [ContractParameter] - Call to OnUpdate failed System.IndexOutOfRangeException: Array index is out of range.
  at CBAttributeMapSO.GetAtt (Double lat, Double lon) [0x00000] in <filename unknown>:0 
  at ScienceUtil.GetExperimentBiome (.CelestialBody body, Double lat, Double lon) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Parameters.CollectScienceCustom.OnUpdate () [0x00000] in <filename unknown>:0 
  at Contracts.ContractParameter.Update () [0x00000] in <filename unknown>:0 
```

**Comment by thewebbooth** [comment]
Yep, ScienceUtil.GetExperimentBiome is a KSP built in function.  This is going to hit everyone.
I have asked Thomas P if there is anything I need to do.

The error you are including there is a ContractConfigurator error but it is still calling ScienceUtil.GetExperimentBiome.  There probably isn't anything nightingale can do either.

**Comment by Sigma88** [comment]
could you try adding this cfg to your game and tell me if it fixes your issue?

```
@Kopernicus:FINAL
{
    %useOnDemand = false
}```

**Comment by Sigma88** [comment]
idk what problems you are having, but If I call 
```
CBAttributeMapSO.GetAtt(0.5,0.5)
```

on any planet in OPM I don't get any errors

**Comment by Awfullyfishy** [comment]
My bad, I'm no coder but I'm trying to help in any way I can, no matter how clumsy.

And I've tried the above with no change at all. Tried uninstalling ResearchBodies with no luck either just a slightly different looking error.

```
[EXC 15:53:54.549] IndexOutOfRangeException: Array index is out of range.
	CBAttributeMapSO.GetAtt (Double lat, Double lon)
	ScienceUtil.GetExperimentBiome (.CelestialBody body, Double lat, Double lon)
	ScienceChecklist.xScienceEventHandler.RecalculateSituation ()
	ScienceChecklist.xScienceEventHandler.UpdateSituation ()
	ScienceChecklist.xScienceEventHandler.Update ()
	ScienceChecklist.ScienceChecklistAddon.Update ()
```

**Comment by Sigma88** [comment]
what versions of kopernicus and OPM are you using?

**Comment by thewebbooth** [comment]
Hi Sigma88, thank you for looking at this.

**Comment by Awfullyfishy** [comment]
Running OPM 1.2.5 and Kopernicus 1.3.1.6, tried reverting to 1.3.1.5 earlier with no luck so I'm back to latest.

**Comment by Sigma88** [comment]
@Awfullyfishy could you please try to find out which is the simplest installation which causes your bug?

here are some combinations that might or might not work:

- `KSP 1.3.1` + `x science v5.11`
- `KSP 1.3.1` + `x science v5.11` + `Kopernicus 1.3.1-6`
- `KSP 1.3.1` + `x science v5.11` + `Kopernicus 1.3.1-3`
- `KSP 1.3.1` + `x science v5.11` + `Kopernicus 1.3.1-6` + `OPM_Galileo v1.2.5`
- `KSP 1.3.1` + `x science v5.11` + `Kopernicus 1.3.1-3` + `OPM_Galileo v1.2.4`

**Comment by Awfullyfishy** [comment]
Tried deleting the OPM and Kopernicus folders from my GameData, issue is gone. 
Going to do the above now!

**Comment by Awfullyfishy** [comment]
Status so far:

- KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-6 + OPM_Galileo v1.2.5
The error is still here! Good news I guess?
- KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-3 + OPM_Galileo v1.2.4
- KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-6
- KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-3
- KSP 1.3.1 + x science v5.11

**Comment by Sigma88** [comment]
do you do something specific to get this issue?

I have installed:

- `KSP 1.3.1` + `x science v5.11` + `Kopernicus 1.3.1-6` + `OPM_Galileo v1.2.5`

started a career, put a mk1pod on the pad and opened x science

this is the result:

![image](https://user-images.githubusercontent.com/12640834/36314302-ab46a352-1334-11e8-9722-13f516e7af1a.png)


I don't get any errors

**Comment by Awfullyfishy** [comment]
I don't check that window at all, instead what I do is launch a craft with a science part, check the Science Here and Now window, which shows the experiment available on the pad, then I use the debug menu to change my orbit around the Minmus and then check the window again to see what it shows as well as the console.

In other news, downgrading to KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-3 + OPM_Galileo v1.2.4 has removed the issue.

![](https://puu.sh/zp4hy/435e8eb989.jpg)

![](https://puu.sh/zp4i3/5ae1abc5b1.jpg)

![](https://puu.sh/zp4ir/84a15a0377.jpg)

**Comment by Sigma88** [comment]
this might just be an issue with editing crafts around another body, have you tried by going to minmus without cheats?

**Comment by Awfullyfishy** [comment]
That's how I first encountered the bug, sent a flyby drone around Minmus and was very confused why x science wasn't working, I could still use my experiments after all. Checked the console and found the error.

I can always try it again with this simple installation, in the mean time back on KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-6 + OPM_Galileo v1.2.5 and:


![](https://puu.sh/zp4u0/6ec3061ff4.jpg)

![](https://puu.sh/zp4uo/39744f7b23.jpg)

![](https://puu.sh/zp4zQ/ea7b8f9605.jpg)

**Comment by Awfullyfishy** [comment]
KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-6 + OPM_Galileo v1.2.5, just tried getting to Minmus without cheats and:

![](https://puu.sh/zp4GG/61a4ccc6a7.jpg)

![](https://puu.sh/zp4Qr/0d708e9e60.jpg)

![](https://puu.sh/zp4S2/18cf2ab5fc.jpg)

**Comment by Awfullyfishy** [comment]
KSP 1.3.1 + x science v5.11 + Kopernicus 1.3.1-6 also doesn't have the issue.

**Comment by Sigma88** [comment]
ok, this is a kopernicus issue

I will open an issue on there and we will take a look to see what is going wrong

thanks for reporting this bug 👍

**Comment by Awfullyfishy** [comment]
Alright, thanks for the help in figuring out the cause!

**Comment by Sigma88** [comment]
would you guys mind testing if this solves your problem?

[Kopernicus-release-1.3.1-6-6-gb473f96-2018-02-16.zip](https://github.com/thewebbooth/KSP-X-Science/files/1732957/Kopernicus-release-1.3.1-6-6-gb473f96-2018-02-16.zip)

**Comment by Awfullyfishy** [comment]
Woah, didn't expect you to work away at it right away! 

Yeah that solved the problem, no errors at all around Minmus and OPM bodies! Thank you _so much!_
